#!/usr/bin/env bash
#UFUNCTION=自动同步当前项目至gitee仓库c
  

chmod +x makelist.sh 
./makelist.sh 
pwd
git status
git add .
if [[ $# -eq 0 ]];then
	dat=$(date +%Y/%m/%d\ %H:%M:%S)
else
	dat=$*
fi
git commit -m "$dat"  
git push

