#!/usr/bin/env bash
#-------------------------------------------------------
#	FileName	: icheck.sh
#	Author		：hpy
#	Date		：2021年04月26日
#	Description	：实时检测脚本verilog代码是否有错误
#-------------------------------------------------------
#UFUNCTUION=实时检测脚本verilog代码是否有错误
#run脚本主函数
error=0
src="$(find -name "*.v")"
lfile=""
cfile=""
ltime=""
ctime=""
main(){
    info=$(iverilog  -o /tmp/wave $src) &> /dev/null &  #综合verilog代码
    while true 
    do 
        cfile=$(find . -type f -mmin 1  | xargs ls -ta | head -n +1)
        if [ ${#cfile} -eq 0 ] ; then 
            sleep 1
        elif [[ "$cfile" != "$lfile" ]] ;then 
            mclear
            #echo "文件不等不等"
            info=$(iverilog  -o /tmp/wave $src) &> /dev/null &  #综合verilog代码
            ctime=$(stat -c %y $cfile)
            ltime=$ctime 
            lfile=$cfile 
            error=1
         else
            ctime=$(stat -c %y $lfile)
            if [[ "$ctime" != "$ltime" ]] ;then 
                mclear
                #echo "时间不等"
                info=$(iverilog  -o /tmp/wave $src) &> /dev/null &  #综合verilog代码
                ltime=$ctime 
            fi 
        fi 
        
        sleep 1
    done 
}


function mclear() {
    
    local j=0
    while [ $j -lt 10 ]
    do 
        echo 
    done 
}


main $*
