#!/usr/bin/env bash
#-------------------------------------------------------
#	FileName	: hp
#	Author		：hpy
#	Date		：2021年04月25日
#	Description	：常用命令记录，自用
#-------------------------------------------------------
#UFUNCTION=一些常用工具的常用指令

cd $(dirname $0)
root="./src"
main(){
    if [[ $1 == "-h" ]] || [[ $1 == "-help" ]] ; then 
cat<<EOF
    Usage: mdx [option]
    mdx             搜索
    mdx add         添加新的内容说明
    mdx push        将更新后的数据同步到云端
    mdx pull        拉取云端最新资源到本地

EOF
    exit 0
    fi 

    if [ -d $root ] ; then 
        if [[ $1 == "add" ]] ; then # 添加内容
            fish -c "open $root > /dev/null ^ /dev/null &"
        elif [[ $1 == "push" ]] ; then  # 同步修改后的数据
            cd ..
            ./upCloud
        elif [[ $1 == "pull" ]] ; then  # 拉取仓库数据到本地
            cd ..
            git pull 
        else 
            cd $root
            dis
        fi 
    else 
        echo "不存在路径$root "
    fi   
}

function dis() {
    PS3="按提示输入序号："
    select i in $(ls) quit 
    do 
        if [[ $i == "quit" ]] ; then 
            exit 0 
        elif [ -d $i ] ; then 
            clear  
            cd $i
            dis 
        elif [ -f $i ] ; then 
            echo 
            echo " >>> $i <<<"
            cat $i
            echo 
            exit 0 
        fi 
    done 

}





#-------------------------------------
main $* 